eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
logging:
  file: bookService.log
management:
    endpoints:
        web:
            exposure:
                include: '*'
    security:
        enabled: false
server:
    servlet:
        contextPath: /bookService
spring:
    application:
        name: book-service
    cloud:
        config:
            uri: http://localhost:8888
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/bookdb
        username: root
    jpa:
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true
