eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
server:
    port: 8765
spring:
    application:
        name: gateway-server
        
zuul:
  routes:
    customer-service:
      path: /**
      url: http://localhost:8765/customer-service
