eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
logging:
  file: registeryServer.log
server:
    port: 8761
spring:
    application:
        name: registery-server
